services:
  - type: web
    name: fastapi
    env: python
    buildCommand: "pip install -r requirements-prod.txt"
    startCommand: "uvicorn main:app --host 0.0.0.0 --port $PORT"
    envVars:
      - key: DATABASE_URL
        sync: false
      - key: SECRET_KEY
        sync: false
